version: '2'

services:
  ueransim:
    privileged: true
    build: ./config
    image: docker_ueransim
    stdin_open: true
    tty: true
    volumes:
      - ./config:/mnt/ueransim
    expose:
      - "/38412/sctp:38412/sctp"
      - "2152/udp:2152/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks: 
      ueransim_vlan:
        
    environment:
      - MCC=${MCC}
      - MNC=${MNC}
      - UE_KEY=${UE_KEY}
      - UE_OP=${UE_OP}
      - UE_AMF_AUTH=${UE_AMF_AUTH}
      - UE_IMEI=${UE_IMEI}
      - UE_IMSI=${UE_IMSI}
      - UE_DNN_NAME=${UE_DNN_NAME}
      - GNB_AMF_IP=${GNB_AMF_IP}
      - TAC=${TAC}
      - NSSAI_SST=${NSSAI_SST}
      - NSSAI_SD=${NSSAI_SD}
      - APN_NAME=${APN_NAME}
  
networks:
  ueransim_vlan:
    driver: macvlan
    driver_opts:
      parent: ens224
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.10/28
          gateway: 10.1.1.1
          ip_range: 10.1.1.0/28
